// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/aliirsyaadn/mekari-technical-assessment/config"
	"github.com/aliirsyaadn/mekari-technical-assessment/handler"
	"github.com/aliirsyaadn/mekari-technical-assessment/repository"
	"github.com/aliirsyaadn/mekari-technical-assessment/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitServer() *gin.Engine {
	sugaredLogger := config.InitLogger()
	db := config.InitDatabase()
	employeeRepository := repository.NewEmployeeRepository(sugaredLogger, db)
	employeeService := service.NewEmployeeService(sugaredLogger, employeeRepository)
	employeeHandler := handler.NewEmployeeHandler(sugaredLogger, employeeService)
	engine := provideRouter(employeeHandler)
	return engine
}
